#!/bin/bash

cd ..

mkdir log

cd fastq

filenames=(`ls *.fastq`)

sampleNames[0]=""

thisBaseName=`basename $0`
#pwd
echo "#generated by $thisBaseName" > ../log/tophat.shvar


for((i=0;i<${#filenames[@]};i++)); do
	sampleNames[$i]=`echo ${filenames[$i]/.fastq/} | tr "-" "_" | tr "." "_"`
	#echo ${sampleNames[$i]}
	echo ${sampleNames[$i]}=${filenames[$i]} >> ../log/tophat.shvar
done


sampla=`echo -n ${sampleNames[@]} | tr " " "," | tr -d "\n"`	
echo Samples=$sampla >> ../log/tophat.shvar

